<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA0uKFOh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA0uKFOh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA0uKFOh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA0uKFOh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA0uKFOh\App_KernelDevDebugContainer([
    'container.build_hash' => 'A0uKFOh',
    'container.build_id' => '3558d394',
    'container.build_time' => 1713270418,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA0uKFOh');
